version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
    - 8.36.2
    - 8.37.0
    - 8.38.0
  - dependency-name: doctrine/dbal
    versions:
    - 2.13.0
    - 3.0.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.3
  - dependency-name: facade/ignition
    versions:
    - 2.5.10
    - 2.5.11
    - 2.5.12
    - 2.5.13
    - 2.5.9
  - dependency-name: laravel/tinker
    versions:
    - 2.6.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.3.0
  - dependency-name: nunomaduro/larastan
    versions:
    - 0.6.13
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.1.0
    - 3.1.1
  - dependency-name: laravel-mix
    versions:
    - 6.0.16
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: react-bootstrap
    versions:
    - 1.4.3
    - 1.5.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: react-toastify
    versions:
    - 7.0.1
    - 7.0.2
